# Generated by Django 5.2.12 on 2026-03-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome interno para identificação', max_length=100, verbose_name='Nome do Anúncio')),
                ('codigo_html', models.TextField(help_text='Cole aqui o script do Google AdSense ou outro código de anúncio', verbose_name='Código HTML')),
                ('posicao', models.CharField(choices=[('topo', 'Topo da Página'), ('meio', 'Entre Produtos'), ('rodape', 'Rodapé da Página'), ('lateral', 'Lateral')], default='meio', max_length=20, verbose_name='Posição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição dentro da posição', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['posicao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do produto exibido no site', max_length=255, verbose_name='Título')),
                ('imagem_url', models.URLField(blank=True, help_text='Link externo da imagem do produto', max_length=500, null=True, verbose_name='URL da Imagem')),
                ('imagem', models.ImageField(blank=True, help_text='Ou faça upload de uma imagem local', null=True, upload_to='produtos/%Y/%m/', verbose_name='Imagem (Upload)')),
                ('link_afiliado', models.URLField(help_text='Link de afiliado do Mercado Livre', max_length=500, verbose_name='Link Afiliado')),
                ('preco', models.CharField(blank=True, help_text="Ex: R$ 99,90 ou 'A partir de R$ 49,90'", max_length=50, null=True, verbose_name='Preço')),
                ('preco_original', models.CharField(blank=True, help_text='Preço antes do desconto (riscado). Ex: R$ 149,90', max_length=50, null=True, verbose_name='Preço Original')),
                ('destaque', models.BooleanField(default=False, help_text='Produtos em destaque aparecem primeiro', verbose_name='Destaque')),
                ('ativo', models.BooleanField(default=True, help_text='Apenas produtos ativos são exibidos no site', verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-destaque', 'ordem', '-criado_em'],
            },
        ),
    ]
