# Generated by Django 5.2.12 on 2026-03-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_afiliado', models.URLField(help_text='Cole aqui o link do produto do Mercado Livre (ex: https://mercadolivre.com.br/... ou https://meli.la/...)', max_length=500, verbose_name='Link Afiliado')),
                ('titulo', models.CharField(blank=True, help_text='Extraído automaticamente do Mercado Livre', max_length=500, verbose_name='Título')),
                ('imagem_url', models.URLField(blank=True, help_text='Extraída automaticamente do Mercado Livre', max_length=500, verbose_name='URL da Imagem')),
                ('preco', models.CharField(blank=True, help_text='Extraído automaticamente do Mercado Livre', max_length=100, verbose_name='Preço')),
                ('preco_original', models.CharField(blank=True, help_text='Preço antes do desconto (se houver)', max_length=100, verbose_name='Preço Original')),
                ('descricao', models.TextField(blank=True, help_text='Extraída automaticamente do Mercado Livre', verbose_name='Descrição')),
                ('url_final', models.URLField(blank=True, help_text='URL real do produto após redirecionamentos', max_length=500, verbose_name='URL Final do Produto')),
                ('status_extracao', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando...'), ('sucesso', 'Extraído com Sucesso'), ('erro', 'Erro na Extração')], default='pendente', max_length=20, verbose_name='Status da Extração')),
                ('erro_extracao', models.TextField(blank=True, help_text='Detalhes do erro caso a extração falhe', verbose_name='Erro da Extração')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ultima_extracao', models.DateTimeField(blank=True, null=True, verbose_name='Última Extração')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_automaticos', to='produtos.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto Automático',
                'verbose_name_plural': 'Produtos Automáticos',
                'ordering': ['-destaque', 'ordem', '-criado_em'],
            },
        ),
    ]
