# Generated by Django 5.2.12 on 2026-03-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtoautomatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome para identificação (ex: 'Atualização Manhã', 'Atualização Noite')", max_length=100, verbose_name='Nome do Agendamento')),
                ('horario', models.TimeField(help_text='Horário em que a atualização será executada (ex: 08:00, 14:00, 20:00)', verbose_name='Horário de Execução')),
                ('dias_semana', models.CharField(choices=[('todos', 'Todos os dias'), ('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo'), ('seg_sex', 'Segunda a Sexta')], default='todos', help_text='Em quais dias este agendamento deve rodar', max_length=10, verbose_name='Dias da Semana')),
                ('ativo', models.BooleanField(default=True, help_text='Ative ou desative este agendamento', verbose_name='Ativo')),
                ('atualizar_apenas_ativos', models.BooleanField(default=True, help_text="Se marcado, atualiza apenas produtos com status 'Ativo'", verbose_name='Apenas produtos ativos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agendamento de Atualização',
                'verbose_name_plural': 'Agendamentos de Atualização',
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='LogAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('total_produtos', models.IntegerField(default=0, verbose_name='Total de Produtos')),
                ('sucesso', models.IntegerField(default=0, verbose_name='Sucesso')),
                ('erros', models.IntegerField(default=0, verbose_name='Erros')),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes da execução', verbose_name='Detalhes')),
                ('duracao_segundos', models.FloatField(default=0, verbose_name='Duração (segundos)')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='produtos.agendamentoatualizacao', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Log de Atualização',
                'verbose_name_plural': 'Logs de Atualização',
                'ordering': ['-executado_em'],
            },
        ),
    ]
