# Generated by Django 5.2.12 on 2026-03-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_agendamentoatualizacao_logatualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoautomatico',
            name='falhas_consecutivas',
            field=models.IntegerField(default=0, help_text='Número de tentativas de atualização que falharam. Ao atingir limite, produto é desativado automaticamente.', verbose_name='Falhas Consecutivas'),
        ),
        migrations.AddField(
            model_name='produtoautomatico',
            name='motivo_desativacao',
            field=models.TextField(blank=True, help_text='Registra o motivo automático de desativação (ex: 5 falhas consecutivas)', verbose_name='Motivo da Desativação'),
        ),
    ]
