# Generated by Django 5.2.12 on 2026-03-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produtoautomatico_falhas_consecutivas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privacidade', 'Política de Privacidade'), ('termos', 'Termos de Uso'), ('afiliados', 'Divulgação de Afiliados')], max_length=20, unique=True, verbose_name='Tipo de Documento')),
                ('texto_html', models.TextField(help_text='Use HTML para formatar (tags: p, h2, h3, b, i, ul, li, etc)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Documento Legal',
                'verbose_name_plural': 'Documentos Legais',
                'ordering': ['tipo'],
            },
        ),
    ]
