# Generated by Django 5.2.12 on 2026-03-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_documentolegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoautomatico',
            name='plataforma',
            field=models.CharField(choices=[('mercado_livre', 'Mercado Livre'), ('amazon', 'Amazon'), ('shopee', 'Shopee'), ('shein', 'Shein'), ('outro', 'Outro')], default='outro', help_text='Detectada automaticamente pela URL do link', max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='descricao',
            field=models.TextField(blank=True, help_text='Extraída automaticamente', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Extraída automaticamente', max_length=500, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='link_afiliado',
            field=models.URLField(help_text='Cole o link do produto (Mercado Livre, Amazon, Shopee, Shein, etc)', max_length=500, verbose_name='Link Afiliado'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='preco',
            field=models.CharField(blank=True, help_text='Extraído automaticamente', max_length=100, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='titulo',
            field=models.CharField(blank=True, help_text='Extraído automaticamente', max_length=500, verbose_name='Título'),
        ),
    ]
