# Generated by Django 5.2.12 on 2026-03-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_escalonamentoconfig'),
        ('produtos', '0006_produtoautomatico_plataforma_and_more'),
    ]

    operations = [
    ]
