# Generated by Django 5.2.12 on 2026-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_escalonamentoconfig_session_timeout'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produtoautomatico',
            name='idx_status_extracao',
        ),
        migrations.RemoveIndex(
            model_name='produtoautomatico',
            name='idx_ativo',
        ),
        migrations.RemoveIndex(
            model_name='produtoautomatico',
            name='idx_ultima_extracao',
        ),
        migrations.RemoveIndex(
            model_name='produtoautomatico',
            name='idx_falhas_consecutivas',
        ),
        migrations.RemoveIndex(
            model_name='produtoautomatico',
            name='idx_ultima_extracao_ativo',
        ),
        migrations.RenameIndex(
            model_name='produtoautomatico',
            new_name='idx_ativo_status',
            old_name='idx_ativo_status_extracao',
        ),
        migrations.RenameIndex(
            model_name='produtoautomatico',
            new_name='idx_falhas_ativo',
            old_name='idx_falhas_consecutivas_ativo',
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='falhas_consecutivas',
            field=models.IntegerField(db_index=True, default=0, help_text='Número de tentativas de atualização que falharam. Ao atingir limite, produto é desativado automaticamente.', verbose_name='Falhas Consecutivas'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='motivo_desativacao',
            field=models.TextField(blank=True, help_text='Registra o motivo automático de desativação (ex: falhas consecutivas)', verbose_name='Motivo da Desativação'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='status_extracao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando...'), ('sucesso', 'Extraído com Sucesso'), ('erro', 'Erro na Extração')], db_index=True, default='pendente', max_length=20, verbose_name='Status da Extração'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='ultima_extracao',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Última Extração'),
        ),
        migrations.AddIndex(
            model_name='produtoautomatico',
            index=models.Index(fields=['-ultima_extracao', 'ativo'], name='idx_ultima_ext_ativo'),
        ),
    ]
