# Generated by Django 5.2.12 on 2026-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_consolidate_produto_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoAutomaticoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Automático',
                'verbose_name_plural': 'Produtos Automáticos',
                'ordering': ['-destaque', 'ordem', '-criado_em'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('produtos.produtoautomatico',),
        ),
        migrations.CreateModel(
            name='ProdutoManualProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Manual',
                'verbose_name_plural': 'Produtos Manuais',
                'ordering': ['-destaque', 'ordem', '-criado_em'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('produtos.produtoautomatico',),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='link_afiliado',
            field=models.URLField(help_text='Cole o link do produto (Mercado Livre, Amazon, Shopee, Shein, etc) ou deixe em branco para manual', max_length=500, verbose_name='Link Afiliado'),
        ),
    ]
