# Generated by Django 5.2.12 on 2026-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produtoautomaticoproxy_produtomanualproxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoautomatico',
            name='imagem_url',
            field=models.URLField(blank=True, help_text='Extraída automaticamente', max_length=3000, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='link_afiliado',
            field=models.URLField(help_text='Cole o link do produto (Mercado Livre, Amazon, Shopee, Shein, etc) ou deixe em branco para manual', max_length=3000, verbose_name='Link Afiliado'),
        ),
        migrations.AlterField(
            model_name='produtoautomatico',
            name='url_final',
            field=models.URLField(blank=True, help_text='URL real do produto após redirecionamentos', max_length=3000, verbose_name='URL Final do Produto'),
        ),
    ]
