# Generated by Django 5.2.12 on 2026-03-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produtoautomatico_imagem_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente', max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(help_text='Com DDD (exemplo: 11999999999)', max_length=20, verbose_name='Telefone')),
                ('canal_preferido', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('ambos', 'Email e WhatsApp')], default='email', max_length=20, verbose_name='Canal Preferido de Contato')),
                ('receber_promocoes', models.BooleanField(default=True, help_text='Enviar notificações de ofertas e descontos', verbose_name='Receber Promoções')),
                ('receber_analises', models.BooleanField(default=True, help_text='Enviar análises de produtos e comparativos', verbose_name='Receber Análises')),
                ('receber_atualizacoes', models.BooleanField(default=True, help_text='Enviar notícias e atualizações do site', verbose_name='Receber Atualizações')),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Cliente ativo/inativo', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('ip_origem', models.GenericIPAddressField(blank=True, help_text='IP do navegador ao fazer cadastro', null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Informações do navegador/device', verbose_name='User Agent')),
                ('confirmado', models.BooleanField(default=False, help_text='Cliente confirmou email (double-opt-in)', verbose_name='Email Confirmado')),
                ('token_confirmacao', models.CharField(blank=True, default='', max_length=100, verbose_name='Token de Confirmação')),
            ],
            options={
                'verbose_name': 'Cliente / Contato',
                'verbose_name_plural': 'Clientes / Contatos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['email'], name='idx_cliente_email'), models.Index(fields=['ativo', '-criado_em'], name='idx_cliente_ativo_data')],
            },
        ),
    ]
