# Generated by Django 5.2.12 on 2026-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0013_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_manutencao', models.BooleanField(default=False, help_text='Marque para ativar modo de manutenção', verbose_name='Site em Manutenção')),
                ('titulo', models.CharField(default='Sistema em Manutenção', help_text='Título exibido no topo da página de manutenção', max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(default='Estamos realizando uma atualização programada. Retorne em breve!', help_text='Mensagem detalhada exibida aos clientes (suporta HTML básico)', verbose_name='Mensagem de Manutenção')),
                ('tempo_estimado_minutos', models.IntegerField(default=30, help_text='Tempo estimado para conclusão da manutenção', verbose_name='Tempo Estimado de Retorno (minutos)')),
                ('mostrar_tempo_estimado', models.BooleanField(default=True, help_text="Se ativo, exibe 'Tempo estimado de retorno: X min'", verbose_name='Exibir Tempo Estimado')),
                ('email_contato', models.EmailField(blank=True, help_text='Email para dúvidas (opcional)', max_length=254, verbose_name='Email de Contato')),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Quando a manutenção começou', null=True, verbose_name='Data/Hora de Início')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Manutenção do Site',
                'verbose_name_plural': 'Configuração de Manutenção do Site',
            },
        ),
    ]
